# Generated by Django 3.1.7 on 2021-04-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubexapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
