# Generated by Django 3.1.7 on 2021-04-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubexapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('video_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
