# Generated by Django 3.1.7 on 2021-04-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubexapp', '0002_auto_20210415_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(default='No Category Selected', max_length=30),
        ),
    ]
