# Generated by Django 3.1.7 on 2021-04-08 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubexapp', '0002_auto_20210408_1235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programs',
            new_name='Program',
        ),
    ]
