# Generated by Django 3.1.7 on 2021-04-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='subscription',
            field=models.CharField(choices=[('12 Months', '12 Months: $100'), ('1 Month', '1 Month: $10'), ('No active subscription', 'No active subscription')], default='No active subscription', max_length=50),
        ),
    ]
